
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Myheader  from "../components/header/Myheader"

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="Ko">
     
    
      <body className="bg-white">
        <Myheader />
        {children}
        
        </body>
     
    </html>
  )
}
